### ISSUE TITLE
[Bug] Error prevent bulletin creation

### ISSUE THREAD

**Issue by ad-olfo** [AndrGab/medirepoWeb#68]
When we try to create a new bulletin, the form is not sent and this error output in console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attendance')
    at BulletinAdd.js:102:41
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.throw (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:29:9)
```

Also, error `Failed to load resource: the server responded with a status of 500 ()` with `https://elderly-joyous-pangolin.gigalixirapp.com/api/bulletins/list`

**Comment by AndrGab** [comment]
backend was fixed..
thanks @41646F6C666F
